extends Node

const GameServiceFixture = preload("res://scripts/game_service.gd")

func _ready() -> void:
    print("TEST_RUNNER_ARGS: ", OS.get_cmdline_user_args())
    if "--test" in OS.get_cmdline_user_args():
        _run()

func _run() -> void:
    # GameService is a legacy offline fixture only; production games use AIService -> Bridge -> core.
    var fixture := GameServiceFixture.new()
    add_child(fixture)
    fixture.new_game(3, 2, 12345)
    assert(fixture.state.players.size() == 3)
    assert(fixture.state.players[0].cards.size() == 20)
    assert(fixture.state.deck.size() == 18)
    assert(fixture.select_discard(0))
    assert(AIService.debug_validate_replay_start_step())
    assert(AIService.debug_validate_replay_restore_payload({"steps": [{"state": {"turnCount": 0}, "action": {"type": "start"}}]}))
    assert(AIService.debug_validate_protocol_version())
    assert(AIService.debug_runtime_launch_kind("custom-bridge", "", false) == "command")
    assert(AIService.debug_runtime_launch_kind("", "", true) == "bundled")
    assert(AIService.debug_runtime_launch_kind("", "E:/project/daer", false) == "development")
    assert(AIService.debug_runtime_launch_kind("", "E:/project/daer", true) == "development")
    assert(AIService.debug_runtime_launch_kind("", "", false) == "missing")
    assert(AIService.debug_bundled_bridge_version_matches(ProjectSettings.globalize_path("res://bridge/daer-ai-server.cmd")))
    var session_id := AIService.debug_runtime_session_id_for(8123, 4567)
    assert(session_id == "godot-8123-4567")
    var first_session_port := AIService.debug_runtime_port_for_session(8123, 0)
    assert(first_session_port >= 49152)
    assert(first_session_port != AIService.debug_runtime_port_for_session(8123, 1))
    var session_health := {"ok": true, "protocolVersion": "daer-godot-v2", "runtimeVersion": "daer-bridge-session-v6", "sessionId": session_id}
    assert(AIService.debug_runtime_response_matches_session(session_health, session_id))
    assert(not AIService.debug_runtime_response_matches_session(session_health, "godot-8124-4567"))
    assert(AIService.debug_runtime_environment_prefix_for_session(first_session_port, session_id, 8123).contains("DAER_GODOT_SESSION_ID=godot-8123-4567"))
    assert(AIService.debug_runtime_environment_prefix_for_session(first_session_port, session_id, 8123).contains("DAER_GODOT_PARENT_PID=8123"))
    assert(AIService.debug_should_advance_session_port(200, {}))
    assert(not AIService.debug_should_advance_session_port(0, {}))
    assert(not AIService.debug_should_advance_session_port(200, {"ok": true}))
    assert(not AIService.debug_http_request_is_busy())
    assert(AIService.debug_runtime_http_timeout_seconds() == 3.0)
    var runtime_session_id := AIService.debug_runtime_session_id()
    assert(AIService.debug_should_restore_startup_game({"ok": true, "protocolVersion": "daer-godot-v2", "runtimeVersion": "daer-bridge-session-v6", "sessionId": runtime_session_id, "activeGame": true}))
    assert(not AIService.debug_should_restore_startup_game({"ok": true, "protocolVersion": "daer-godot-v2", "runtimeVersion": "daer-bridge-session-v6", "sessionId": runtime_session_id, "activeGame": false}))
    assert(not AIService.debug_should_restore_startup_game({"ok": true, "protocolVersion": "daer-godot-v2", "activeGame": true}))
    assert(AIService.debug_should_reconcile_new_game_state(4, 4, {}, {}))
    assert(not AIService.debug_should_reconcile_new_game_state(4, 5, {}, {}))
    assert(not AIService.debug_should_reconcile_new_game_state(4, 4, {"phase": "discarding"}, {}))
    assert(not AIService.debug_should_reconcile_new_game_state(4, 4, {}, {"phase": "discarding"}))
    assert(get_parent().debug_validate_hand_groups())
    assert(get_parent().debug_validate_near_hand_groups())
    assert(get_parent().debug_validate_manual_hand_group_split())
    assert(get_parent().debug_validate_free_hand_column_drop())
    assert(get_parent().debug_validate_hand_arrangement_mode())
    assert(get_parent().debug_validate_hand_arrangement_toggle())
    var previous_hand_mode := str(AppState.settings.get("hand_arrangement_mode", "group"))
    AppState.settings["hand_arrangement_mode"] = "free"
    assert(get_parent()._hand_arrangement_mode() == "group")
    AppState.settings["hand_arrangement_mode"] = previous_hand_mode
    assert(get_parent().debug_validate_locked_hand_presentation())
    var hand_with_locked := [
        {"id": "k1", "value": 3, "size": "small"},
        {"id": "k2", "value": 3, "size": "small"},
        {"id": "k3", "value": 3, "size": "small"},
        {"id": "single", "value": 8, "size": "big"},
    ]
    var integrated_groups: Array = get_parent()._hand_display_groups(hand_with_locked, [{"cardIds": ["k1", "k2", "k3"], "label": "坎"}])
    assert(not integrated_groups.is_empty())
    assert(str(integrated_groups[0].get("kind", "")) == "locked")
    assert(Array(integrated_groups[0].get("cards", [])).size() == 3)
    assert(str(integrated_groups[0].get("label", "")).begins_with("锁"))
    assert(get_parent()._hand_drop_reorders_cards())
    var group_card_dimensions: Vector2 = get_parent()._hand_card_dimensions()
    AppState.settings["hand_arrangement_mode"] = "free"
    var legacy_card_dimensions: Vector2 = get_parent()._hand_card_dimensions()
    AppState.settings["hand_arrangement_mode"] = previous_hand_mode
    assert(group_card_dimensions == legacy_card_dimensions)
    assert(group_card_dimensions.x >= 51.0)
    assert(get_parent().debug_validate_drag_discard_guard())
    assert(get_parent().debug_validate_drag_discard_hit_rect())
    assert(get_parent().debug_validate_free_hand_order())
    assert(get_parent().debug_validate_new_game_auto_hand_layout())
    assert(get_parent().debug_validate_table_layout_scenes())
    assert(get_parent().debug_validate_table_layout_runtime_injection())
    assert(get_parent().debug_validate_opponent_seat_layout())
    assert(get_parent().debug_validate_action_buttons_top_row())
    assert(get_parent().debug_validate_no_placeholder_text())
    assert(get_parent().debug_validate_opponent_public_meld_columns())
    assert(get_parent().debug_validate_center_discard_presentation())
    assert(get_parent().debug_validate_discard_chip_real_art())
    assert(get_parent().debug_validate_opponent_public_card_text())
    assert(get_parent().debug_validate_public_meld_layout_consistency())
    assert(get_parent().debug_validate_ai_action_delay())
    assert(get_parent().debug_validate_response_without_actions())
    assert(get_parent().debug_validate_response_snapshot_change())
    assert(get_parent().debug_validate_deck_stack_presentation())
    assert(get_parent().debug_validate_discard_stack_layout())
    assert(get_parent().debug_validate_table_mirror_layout())
    assert(get_parent().debug_validate_animation_target_routes())
    assert(get_parent().debug_validate_human_auto_retry_guard())
    assert(get_parent().debug_validate_ai_completion_auto_reconcile())
    assert(get_parent().debug_validate_automatic_progress_poll_guard())
    assert(get_parent().debug_validate_ai_step_failure_guard())
    assert(get_parent().debug_validate_free_hand_column_anchor())
    assert(get_parent().debug_validate_player_action_banner())
    assert(get_parent().debug_validate_bao_action_presentation())
    assert(get_parent().debug_validate_human_draw_auto_advance())
    assert(get_parent().debug_validate_response_context())
    var action_station_state := {"currentPlayerIndex": 0, "availableActions": [{"type": "discard", "cards": [{"id": "s1"}]}], "players": [{"cards": [{"id": "s1", "value": 1}]}]}
    assert(get_parent().debug_action_station_text(action_station_state).contains("你的回合"))
    assert(get_parent().debug_action_station_text(action_station_state, "s1").contains("已选 1"))
    assert(get_parent().debug_player_action_hint(action_station_state) == "轮到你")
    assert(get_parent().debug_player_action_hint(action_station_state, "s1").contains("已选 1"))
    assert(get_parent().debug_action_station_text({"currentPlayerIndex": 0, "phase": "response_collecting", "availableActions": [{"type": "pass"}], "discardPile": {"lastDiscard": {"value": 7}, "lastDiscardPlayerIndex": 1}}).contains("合法响应"))
    assert(get_parent().debug_action_station_text({"currentPlayerIndex": 1, "availableActions": [{"type": "discard"}]}).contains("等待 AI 决策"))
    assert(get_parent().debug_validate_decision_policy_labels())
    assert(get_parent().debug_validate_decision_option_metrics())
    assert(get_parent().debug_validate_advice_policy_metadata())
    var suggestion_state := {"availableActions": [{"type": "discard", "cards": [{"id": "s1", "value": 1}]}, {"type": "pass", "cards": []}]}
    assert(get_parent().debug_recommended_legal_discard(suggestion_state, {"action": "discard", "card": {"id": "s1", "value": 1}}).get("id", "") == "s1")
    assert(get_parent().debug_recommended_legal_discard(suggestion_state, {"action": "discard", "card": {"id": "forged", "value": 1}}).is_empty())
    assert(get_parent().debug_recommended_legal_discard(suggestion_state, {"action": "peng", "card": {"id": "s1"}}).is_empty())
    assert(get_parent().debug_validate_tutor_dimension_formatting())
    assert(get_parent().debug_validate_trace_card_formatting())
    assert(get_parent().debug_validate_replay_status())
    assert(get_parent().debug_validate_replay_decision_access())
    assert(get_parent().debug_validate_keyboard_guards())
    assert(get_parent().debug_validate_option_payloads())
    assert(get_parent().debug_validate_option_picker_card_art())
    assert(get_parent().debug_validate_option_picker_grouping())
    assert(get_parent().debug_validate_three_discard_zones())
    assert(get_parent().debug_validate_discard_zone_states())
    assert(get_parent().debug_validate_coordinate_ruler())
    assert(get_parent().debug_validate_discard_zone_orientation())
    assert(get_parent().debug_validate_discard_zone_coordinates())
    assert(get_parent().debug_validate_discard_zone_transparency())
    assert(get_parent().debug_validate_player_hand_transparency())
    assert(get_parent().debug_validate_drag_y_threshold())
    assert(get_parent().debug_validate_public_meld_wrap())
    assert(get_parent().debug_validate_animation_endpoint_contract())
    assert(get_parent().debug_validate_action_animation_routes())
    assert(get_parent().debug_validate_animation_position_routes())
    assert(get_parent().debug_validate_animation_anchor_priority())
    assert(get_parent().debug_validate_game_popup_dismissal())
    assert(get_parent().debug_validate_state_change_modal_dismissal())
    assert(get_parent().debug_validate_opponent_ai_mode())
    assert(get_parent().debug_validate_runtime_policy_mode())
    assert(get_parent().debug_should_auto_advance({"currentPlayerIndex": 1, "isGameOver": false}))
    assert(not get_parent().debug_should_auto_advance({"currentPlayerIndex": 0, "isGameOver": false}))
    assert(get_parent().debug_should_auto_advance({"currentPlayerIndex": 0, "activePlayerIndex": 1, "awaitingHumanInput": false, "isGameOver": false}))
    assert(not get_parent().debug_should_auto_advance({"currentPlayerIndex": 1, "activePlayerIndex": 0, "awaitingHumanInput": true, "isGameOver": false}))
    assert(not get_parent().debug_should_auto_advance({"currentPlayerIndex": 2, "isGameOver": true}))
    fixture.new_game(4, 0, 12345)
    assert(fixture.state.players.size() == 3)
    for player in fixture.state.players:
        assert(player.cards.size() == 20)
    var results: Array = fixture.run_batch(2)
    assert(results.size() == 2)
    var replay_id := "test_replay_contract"
    assert(PersistenceService.debug_validate_replay_id(replay_id))
    assert(not PersistenceService.debug_validate_replay_id("../escape"))
    assert(not PersistenceService.debug_validate_replay_id("nested/path"))
    assert(not PersistenceService.debug_validate_replay_id("x".repeat(65)))
    var replay_file := PersistenceService.save_replay({"game": "daer", "steps": [{"state": {"turnCount": 1}, "action": {"type": "pass"}}]}, replay_id)
    assert(not replay_file.is_empty())
    var replay := PersistenceService.load_replay(replay_file)
    assert(replay.get("game", "") == "daer")
    assert(Array(replay.get("steps", [])).size() == 1)
    assert(PersistenceService.list_replays().any(func(item: Dictionary) -> bool: return item.get("file_name", "") == replay_file))
    assert(PersistenceService.load_replay("replay_../escape.json").is_empty())
    DirAccess.remove_absolute(ProjectSettings.globalize_path("user://replays/" + replay_file))
    print("GAME_SERVICE_TESTS_PASSED")
    get_tree().quit()
